# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
