# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181020_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
