# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181020_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='post',
            field=models.TextField(max_length=50000000),
        ),
    ]
