# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181020_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighbour',
        ),
    ]
