# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_profile_neighbour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
